[book]
authors = ["Furya Labs"]
language = "en"
multilingual = false
src = "src"
title = "The Furya Protocol"

[preprocessor.katex]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
curly-quotes = true
fold = { enable = true, level = 1 }
git-repository-url = "https://github.com/fury-labs/furya"
